hydra:
#  output_subdir: null
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}

run:
  predict: true
  checkpoint_path: ["outputs/cnn_on_ms_poverty/mada_rural_season_notrain/fold_A/epoch=35-step=360-r2/val=0.1586.ckpt",
                    "outputs/cnn_on_ms_poverty/mada_rural_season_notrain/fold_B/epoch=36-step=370-r2/val=0.1076.ckpt",
                    "outputs/cnn_on_ms_poverty/mada_rural_season_notrain/fold_C/epoch=38-step=390-r2/val=-0.0410.ckpt",
                    "outputs/cnn_on_ms_poverty/mada_rural_season_notrain/fold_D/epoch=29-step=300-r2/val=-0.0532.ckpt",
                    "outputs/cnn_on_ms_poverty/mada_rural_season_notrain/fold_E/epoch=44-step=450-r2/val=0.2036.ckpt"]


data:
  dataset_path: ../../../images/seasonal_raw
  labels_name: /../landsat7.csv
  train_batch_size: 64
  inference_batch_size: 64
  num_workers: 8
  val_split: 0.2
  test_split: 0.2
  nature: seasonal
  nightlight: false
  dict_normalize: mean_std_normalize_all.json
  fold_path: folds_mada_rural.pkl

task:
  task: regression

trainer:
  accelerator: gpu
  devices: 1
  max_epochs: 60
  check_val_every_n_epoch: 1

model:
  provider_name: torchvision
  model_name: resnet18
  model_kwargs:
    weights: null
    num_classes: null
    in_chans: null
    output_stride: null
    global_pool: null
  modifiers:
    change_first_convolutional_layer:
      num_input_channels: 64
    change_last_layer:
      num_outputs: 1

optim:
  optimizer:
    adamw: # ['adam', 'sgd', 'adamw', 'adadelta', 'adagrad', 'adamax', 'rmsprop']
      # callable: 'optim.SGD'
      kwargs:
        lr: 1e-4
        weight_decay: 1.0e-05
      scheduler: # Optional, delete key or leave empty to not use any learning rate scheduler
        reduce_lr_on_plateau:
          kwargs:
            threshold: 0.001
          lr_scheduler_config:
            monitor: loss/val  # ['loss/train', 'loss/val', '<metric>/train', '<metric>/val', ...]

  loss: mse_loss
  loss_kwargs:
    reduction: "mean"


  metrics:
    r2:
      callable: "Fmetrics.regression.r2_score"
      kwargs:
        multioutput: "uniform_average"
    mae:
      callable: "Fmetrics.regression.mean_absolute_error"
      kwargs: {}

seed: 42

