hydra:
  run:
    dir: outputs/${run.run_name}

run:
  predict: false
  interpretable: true
  exp_name: 00_tza_popdens
  run_name: ${run.exp_name}-${now:%Y-%m-%d_%H-%M-%S}
  checkpoint_path:

data:
  root: /home/sarah/malpolon_pop_density/malpolon-marbec/examples/POPDENS/
  inputs_path: ${data.root}inputs/landsat/
  labels_path: ${data.root}inputs/labels/
  num_channels: 3
  num_classes: 1
  patch_size: 224
  batch_size: 64
  num_workers: 8
  sample_size: 500

trainer:
  accelerator: gpu
  devices: "auto"
  max_epochs: 60
  val_check_interval: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 100
  detect_anomaly: false

model:
  provider_name: torchvision_segmentation
  model_name: deeplabv3_resnet50
  model_kwargs:
    weights: null
  modifiers:
    change_first_convolutional_layer:
      num_input_channels: ${data.num_channels}
    change_last_layer_dlv3:
      num_outputs: ${data.num_classes}

optim:
  optimizer:
    adamw:
      kwargs:
        lr: 0.001
        weight_decay: 0.5
      scheduler:
        reduce_lr_on_plateau:
          kwargs:
            patience: 6
            eps: 1e-9
            factor: 0.2
          lr_scheduler_config:
            monitor: loss/val
  loss: "huber_loss"
  metrics:
    r2:
      callable: "Fmetrics.regression.r2_score"
    mae:
      callable: "Fmetrics.regression.mean_absolute_error"
      kwargs:
        num_outputs: 1

loggers:
  log_dir_name: ${data.root}logs/
