hydra:
  run:
    dir: /marbec-data/RLS-Australia/malpolon/outputs/${run.run_name}
    
run:
  predict: true
  exp_name: 12_env_reg
  run_name: ${run.exp_name}-${now:%Y-%m-%d_%H-%M}
  checkpoint_path: '/marbec-data/RLS-Australia/malpolon/outputs/12_env_reg-2025-02-06_11-21/last.ckpt'
  pa_predictions_path: '/marbec-data/RLS-Australia/malpolon/outputs/9_env_pa-2025-02-07_11-48-preds/presences.csv'
data:
  root: "/marbec-data/RLS-Australia/malpolon/"
  inputs_path: "/marbec-data/RLS-Australia/malpolon/inputs"
  dataset_name: database_split.csv
  num_classes: &num_classes 1796
  train_batch_size: 64
  inference_batch_size: 16
  num_workers: 8
trainer:
  accelerator: "auto"
  devices: "auto"
  max_epochs: 60
  val_check_interval: 100
  check_val_every_n_epoch: 1
  detect_anomaly: false
model:
  freeze_submodels: false
  submodels:
    env:
      provider_name: torchvision
      model_name: resnet18
      model_kwargs:
        weights: IMAGENET1K_V1
      modifiers:
        change_last_layer:
          num_outputs: *num_classes
        change_first_convolutional_layer:
          num_input_channels: 17
optim:
  optimizer:
    adamw:
      kwargs:
        lr: 1e-3
        weight_decay: 0.1
      scheduler: 
        reduce_lr_on_plateau:
          kwargs:
            patience: 6
            eps: 1e-9
            factor: 0.2
          lr_scheduler_config:
            monitor: loss/val
  loss: "weighted_huber_loss"
  metrics:
    r2:
      callable: "Fmetrics.regression.r2_score"
      kwargs:
        multioutput: "uniform_average"
    mae:
      callable: "Fmetrics.regression.mean_absolute_error"
      kwargs:
        num_outputs: 1
loggers:
  log_dir_name: "/marbec-data/RLS-Australia/malpolon/logs/"
