hydra:
  run:
    dir: /data/data/malpolon/outputs/${run.run_name}
run:
  predict: false
  interpretable: false
  exp_name: 0_envhum_transductif
  run_name: ${run.exp_name}-${now:%Y-%m-%d_%H-%M}
  checkpoint_path: null
data:
  root: /marbec-data/RLS-Australia/malpolon/
  inputs_path: ${data.root}inputs/australia/
  dataset_name: database_transductif.csv
  train_batch_size: 64
  inference_batch_size: 16
  num_workers: 8
  mask_inputs: 0.5
  patch_size: 4
trainer:
  accelerator: "auto"
  devices: "auto"
  max_epochs: 80
  val_check_interval: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 100
  detect_anomaly: false
model:
  freeze_submodels: false
  mae_decoder: true
  submodels:
    envhum:
      provider_name: torchvision
      model_name: resnet18
      model_kwargs:
        weights: IMAGENET1K_V1
      modifiers:
        change_first_convolutional_layer:
          num_input_channels: 19
optim:
  optimizer:
    adamw:
      kwargs:
        lr: 1e-2
        weight_decay: 0.01
      scheduler: 
        reduce_lr_on_plateau:
          kwargs:
            patience: 6
            eps: 1e-9
            factor: 0.2
          lr_scheduler_config:
            monitor: loss/val
  loss: mae_loss
loggers:
  log_dir_name: /data/data/malpolon/logs/
