hydra:
  run:
    dir: ${data.root}outputs/${run.run_name}
  sweep:
    dir: ${data.root}outputs/${run.run_name}
    subdir: Seed-${run.seed}
run:
  inference: false
  testing: true
  interpretable: false
  exp_name: 42_ind_eco_seedtest
  run_name: ${run.exp_name}-${now:%Y-%m-%d_%H-%M}
  checkpoint_path: null #${data.root}outputs/40_mm4_transductif_eco-2026-03-09_18-20/last.ckpt
  pa_predictions_path: null #${data.root}outputs/37_mm4_transductif-2025-12-02_12-47/presences--TH=0.226.csv
  finetuning_mode: null # transductive
  seed: 12
data:
  root: /marbec-data/RLS-Australia/malpolon/
  inputs_path: ${data.root}inputs/australia
  dataset_name: eco_indic_norm.csv
  num_classes: 3
  train_batch_size: 32
  inference_batch_size: 64
  num_workers: 2
trainer:
  accelerator: "auto"
  devices: "auto"
  max_epochs: 25
  val_check_interval: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 100
  detect_anomaly: false
model:
  num_species: ${data.num_classes}
  aggregator: MLP
  freeze_submodels: false
  submodels:
    env:
      provider_name: torchvision
      model_name: resnet18
      checkpoint: null #${data.root}outputs/36_fm_transductif-2025-12-02_08-53/last.ckpt
      model_kwargs:
        weights: IMAGENET1K_V1
      modifiers:
        change_last_layer:
          num_outputs: ${model.num_species}
        change_first_convolutional_layer:
          num_input_channels: 15
    humhd:
      provider_name: torchvision
      model_name: resnet18
      checkpoint: null #${data.root}outputs/36_fm_transductif-2025-12-01_16-53/last.ckpt
      model_kwargs:
        weights: IMAGENET1K_V1
      modifiers:
        change_last_layer:
          num_outputs: ${model.num_species}
        change_first_convolutional_layer:
          num_input_channels: 4
    bathy:
      provider_name: torchvision
      model_name: resnet18
      checkpoint: null #${data.root}outputs/36_fm_transductif-2025-12-01_22-22/last.ckpt
      model_kwargs:
        weights: IMAGENET1K_V1
      modifiers:
        change_last_layer:
          num_outputs: ${model.num_species}
        change_first_convolutional_layer:
          num_input_channels: 1
    dhw:
      provider_name: torchvision
      model_name: resnet18
      checkpoint: null #${data.root}outputs/36_fm_transductif-2025-12-01_16-56/last.ckpt
      model_kwargs:
        weights: IMAGENET1K_V1
      modifiers:
        change_last_layer:
          num_outputs: ${model.num_species}
        change_first_convolutional_layer:
          num_input_channels: 1
optim:
  optimizer:
    adamw:
      kwargs:
        lr: 1e-4
        weight_decay: 1e-4
      scheduler: 
        reduce_lr_on_plateau:
          kwargs:
            patience: 6
            eps: 1e-9
            factor: 0.2
          lr_scheduler_config:
            monitor: loss/val
  loss: "mse_loss"
  metrics:
    r2:
      callable: "Fmetrics.regression.r2_score"
      kwargs:
        multioutput: "uniform_average"
    mae:
      callable: "Fmetrics.regression.mean_absolute_error"
      kwargs:
        num_outputs: 1
loggers:
  log_dir_name: ${data.root}logs/

