hydra:
  run:
    dir: ${data.root}local/outputs/${run.run_name}
run:
  predict: false
  interpretable: false
  exp_name: 0_test_reg
  run_name: ${run.exp_name}-${now:%Y-%m-%d_%H-%M}
  checkpoint_path: null #${data.root}outputs/24_humenv_cat_reg_top100-2025-09-15_15-33/last.ckpt
  pa_predictions_path: null #${data.root}outputs/18_humenv_dhw_cat_pa-2025-07-11_16-53-preds/presences.csv
  top100_path: null #${data.root}outputs/18_humenv_dhw_cat_pa-2025-07-11_16-53-preds/top100-f1.csv
  finetuning_mode: null
data:
  root: /marbec-data/RLS-Australia/malpolon/
  inputs_path: ${data.root}inputs/australia
  dataset_name: database_common.csv
  num_classes: 817
  train_batch_size: 16
  inference_batch_size: 64
  num_workers: 2
trainer:
  accelerator: "auto"
  devices: "auto"
  max_epochs: 60
  val_check_interval: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 100
  detect_anomaly: false
model:
  num_species: ${data.num_classes}
  aggregator: MLP
  freeze_submodels: false
  submodels:
    env:
      provider_name: torchvision
      model_name: resnet18
      checkpoint: null #${data.root}outputs/12_env_reg-2025-03-03_12-06/last.ckpt
      model_kwargs:
        weights: IMAGENET1K_V1
      modifiers:
        change_last_layer:
          num_outputs: ${data.num_classes}
        change_first_convolutional_layer:
          num_input_channels: 15
optim:
  optimizer:
    adamw:
      kwargs:
        lr: 1e-2
        weight_decay: 1e-2
      scheduler: 
        reduce_lr_on_plateau:
          kwargs:
            patience: 6
            eps: 1e-9
            factor: 0.2
          lr_scheduler_config:
            monitor: loss/val
  loss: "mse_loss"
  metrics:
    r2:
      callable: "Fmetrics.regression.r2_score"
      kwargs:
        multioutput: "uniform_average"
    mae:
      callable: "Fmetrics.regression.mean_absolute_error"
      kwargs:
        num_outputs: 1
loggers:
  log_dir_name: ${data.root}local/logs/
