hydra:
  run:
    dir: ${data.root}outputs/${run.run_name}
run:
  predict: false
  interpretable: false
  exp_name: 36_fm_transductif
  run_name: ${run.exp_name}-${now:%Y-%m-%d_%H-%M}
  checkpoint_path: null #${data.root}outputs/32_fm_transductif-2025-11-21_09-16/last.ckpt
data:
  root: /marbec-data/RLS-Australia/malpolon/
  inputs_path: ${data.root}inputs/australia/
  dataset_name: database_transductif.csv
  train_batch_size: 16
  inference_batch_size: 64
  num_workers: 2
  mask_inputs: 0.5
  mae_patch_size: 8
trainer:
  accelerator: "auto"
  devices: "auto"
  max_epochs: 30
  val_check_interval: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 100
  detect_anomaly: false
model:
  freeze_submodels: false
  mae_decoder: ${eval:'${data.mask_inputs} > 0'}
  mae_patch_size: ${data.mae_patch_size}
  submodels:
    env:
      provider_name: torchvision
      model_name: resnet18
      checkpoint: null #${data.root}outputs/32_fm_transductif-2025-11-24_18-42/last.ckpt
      model_kwargs:
        weights: IMAGENET1K_V1
      modifiers:
        change_first_convolutional_layer:
          num_input_channels: 15
optim:
  optimizer:
    adamw:
      kwargs:
        lr: 1e-2
        weight_decay: 1e-2
      scheduler: 
        reduce_lr_on_plateau:
          kwargs:
            patience: 6
            eps: 1e-9
            factor: 0.2
          lr_scheduler_config:
            monitor: loss/val
  loss: mae_loss
loggers:
  log_dir_name: ${data.root}logs/
