# Import Packages pointing to their package folders
[tool.setuptools.package-dir]
malpolon = '.'

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "malpolon"
version = "0.1"
authors = [{name="LIRMM"},
            {name="Marbec"}]
dependencies =  ["hydra-core",
	"pytorch-lightning",
	"scikit-learn",
	"timm",
	"matplotlib",
	"pandas",
    "tensorboard",
    "captum"]
requires-python = ">= 3.7"

